@baseUrl = http://localhost:3333
@AuthToken = {authenticate.response.body.access_token}

POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jhonatan",
  "cpf": "12345678901",
  "password": "123456",
  "role": "ADMIN"
}

###
# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "cpf": "12345678901",
  "password": "123456"
}
